project:
  type: website
  output-dir: _site

website:
  title: "ISSS626 Coursework"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Hands-on Exercise 1"
        menu:
          - text: "Part 1: Geospatial Data Wrangling with R"
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd#part1
          - text: "Part 2: Choropleth Mapping with R"
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd#part2

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: show
    number-sections: false
